### ISSUE TITLE
Construction of the Manually Verified Test Set

### ISSUE THREAD

**Issue by hshreeshail** [gulvarol/bsl1k#11]
I had some queries from the ECCV'20 paper. All points below refer to `Section-3.3.Constructing a manually verified test set`. which describes a two-step procedure for construction.

1] From Step-1:  `yielding 5,826 sign predictions` & `validated 980 signs` & `corrections were provided as labels for the signs marked as incorrect and uncertain signs were removed)`

Q1] Does this mean that there were 5826 predictions from all 3 splits (train/test/val), and of these, only 980 remained when you consider only the test set and remove the incorrect AND/OR uncertain ones?

Q2] What does "corrections" mean - does it mean that the word was changed to match the (incorrectly) captured sign? Does it mean that the correct video clip (of duration 0.6 sec) for that word was found manually?

Q3] Does this mean the corrected signs are part of the 980? 

Q4] Why correct "incorrect" predictions and remove the "uncertain" predictions? Why not correct or remove both?

2] From Step-2:  `annotated a further 2k signs`

Q1] How were these further 2k signs chosen? Randomly from the rest (i.e., signs with peak probability < 0.9)? Highest probability from the rest?

Q2] Why divide the procedure into two parts? Why not just set some lower (i.e., < 0.9), threshold (say 0.8) and then just do Step-1.

**Comment by gulvarol** [comment]
Thanks for your interest, and sorry for the confusing description in the paper.
First of all, the annotator sees the interface in Figure A.4 of the appendix, where they choose between “Yes”, “No” and “Not Sure”. They have the option to type a “correction” in case they click No in the text box that says “enter true sign if incorrect”.
1]

Q1] The manual verification procedure is only for the test set, so all 5826 instances are from the test set, all with >0.9 confidence. We had native BSL signers who annotated a subset of these. After removing “Not Sure” instances, and changing the labels of those marked as “No” with the “corrections” from the text box, we obtain 980 instances with verified ground truth. But note that the native signers did not finish annotating all 5826 instances.

Q2] See above. Correction means entering the true sign manually in the text box if marked No. Note that this is not an easy task for non-native signers, so only the native signers did this.

Q3] Yes, corrected signs are part of the 980 if the word falls in our vocabulary.

Q4] If the annotator is unable to tell if the sign is correctly labeled or not, they may not be able to label it either, so it’s better to remove these instances. This can be due to multiple reasons such as an unrecognized sign.

2] Step 2 is with non-native signers.

Q1] Halfway through the annotation, we recruited non-native signers to accelerate the verification. These 2k annotations were just randomly from the rest within 5826 that were still not verified, i.e., the next batch in the queue waiting to be annotated.

Q2] The first stage of annotation was conducted to perform an initial validation of the effectiveness of automatic annotation via mouthings. Following the positive result of this initial validation, we then sought to increase the number of verified annotations that we could employ to evaluate models (which involved recruiting further annotators).  
Note that Step-1 was with native signers, Step-2 with non-native. This was not our initial plan, but happened naturally along the process when we found more annotators to help us. After completing 0.9, we moved on to 0.8 after submitting this paper; however the yield from lower thresholds is lower, so annotating higher thresholds is more efficient.
Also note that we unfortunately cannot make BSL1K annotations available. So please have a look at our BOBSL annotations (https://www.robots.ox.ac.uk/~vgg/data/bobsl/) instead which has a simpler pipeline (all annotations with native signers).

**Comment by hshreeshail** [comment]
Thank you very much. Really appreciate the detailed response.
