### ISSUE TITLE
Question: Videos do not seem to load correctly  

### ISSUE THREAD

**Issue by walsharry** [gulvarol/bsl1k#3]
Dear Authors, 

I have been trying to use the code by running "python main.py --asl_dataset msasl --checkpoint checkpoint/msasl_i3d_pbsl1k --datasetname msasl --init_cross_language asl_with_bsl --num-classes 1000 --num_gpus 1 --num_in_frames 64 --pretrained misc/pretrained_models/model.pth.tar --ram_data 1 --workers 16" but the data["rgb"] tensor seems to be empty. The output is also showing up blank. 
![Screenshot from 2020-12-22 18-06-56](https://user-images.githubusercontent.com/50142465/102919472-d4b3fc00-4480-11eb-887c-e94f598a936a.png)

This seem to happen on both the WLASL and MSASL datasets. The folder structure is as follows. 
data\
   |-experiments
   |  ---wlasl_i3d_pbsl1k
   |-msasl
   |  ---info
   |  ---videos_original
   |-wlasl
   |  ---info
   |  ---videos_original
   |  -----test
   |  -----train
   |  -----val

What can I do to fix this issue? I understand this is most likely issue with my setup, but any help is very much appreciated. Thanks in advance.

**Comment by gulvarol** [comment]
Could you try with `--ram_data 0` instead, i.e., disabling loading the full dataset in RAM, and using the video files on the fly instead? Note that in order to use the `ram_data` functionality you need to run preprocessing scripts as in [misc/pickle_frames.py](https://github.com/gulvarol/bsl1k/blob/master/misc/pickle_frames.py).
